version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "stabledefusion-dowloader"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
  run:
    desc: Run Go app with environment variables from .env.local file
    cmds:
      - |
        while read -r line; do 
          export $line
        done < .env.local
      - go run . .
