version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "stabledefusion-dowloader"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
  run:
    desc: Run Go app with environment variables from .env.local file
    cmds:
      - export $(grep -v '^#' .env.local | xargs) && go run . .
